apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: {{ .Values.name }}
      containers:
        - name: migrations
          image: {{ .Values.repository }}
          envFrom:
            - configMapRef:
                name: database-common
            - configMapRef:
                name: database-root
            - configMapRef:
                name: admin-panel
          env:
            - name: "MYSQL_READ_USERNAME"
              valueFrom:
                configMapKeyRef:
                  name: database-read
                  key: DATABASE_USERNAME
            - name: "MYSQL_READ_PASSWORD"
              valueFrom:
                configMapKeyRef:
                  name: database-read
                  key: DATABASE_PASSWORD
            - name: "MYSQL_WRITE_USERNAME"
              valueFrom:
                configMapKeyRef:
                  name: database-write
                  key: DATABASE_USERNAME
            - name: "MYSQL_WRITE_PASSWORD"
              valueFrom:
                configMapKeyRef:
                  name: database-write
                  key: DATABASE_PASSWORD